### PR TITLE
Created the template files necessary to use the project in Visual Studio 2017 as a template

### PR DESCRIPTION
**Pull request by chris-lynch**
Hi,
     I created the template files necessary to use the project in Visual Studio 2017 as a template. 

Simply zip up the repository and place it in "Documents\Visual Studio 2017\Templates\ProjectTemplates".

Make sure the zip file doesn't contain a top level folder. if you opened the zip you should see Xamplate.vstemplate and the Xemplate.sln at the top level.

Restart visual studio and create a new Project under Visual C# and "Xamplate" should be at the bottom of the list. If you cant see it then use the search bar.

It also updates the namespace and assembly names of each project.

Chris

### CODE REVIEW

**Comment by tomislaveric** [comment]
Thank you chris for your PR, sorry for the delay, havent received any notification! i am not running a windows machine so i can't test it, but everything seems to be good.

**Comment by chris-lynch** [comment]
Tomis,
    Glad It helped :)

If you also check out the comments in this video you will find some other 
code I wrote to pass parameters to viewmodels.

Feel free to add it if you like.

https://youtu.be/sa-QSIcrIFA

It's a carsandcode video.

Chris

**Comment by tomislaveric** [comment]
Thats funny, carsandcode inspired me and most of the code is from there! I will check it out!

**Comment by chris-lynch** [comment]
Hi
Yes that's where I originally found a reference to xamplate.
Chris

**Pull request merged**
